[tool.ruff]
line-length = 119  # Allow longer lines for ruff than black and isort, for comments and docstrings
target-version = 'py310'
exclude = [
  '.eggs',        # exclude a few common directories in the
  '.git',         # root of the project
  '.history',
  '.hg',
  '.mypy_cache',
  '.tox',
  '.venv',
  '_build',
  'migrations',
  'node_modules',
  'buck-out',
  'build',
  'builds',
  'dist',
]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.history
    | \.hg
    | \.mypy_cache
    | .ruff_cache
    | \.tox
    | \.venv
    | _build
    | node_modules
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
src_paths = ["binary_database_files"]
line_length = 88